logging:
    level:
        ROOT: WARN
        com.kairos: WARN

spring:
    devtools:
        restart:
            enabled: false
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true

server:
    port: 8080
settings:
    cors-origin: http://fizz-buzz-ui.s3-website.eu-west-2.amazonaws.com