logging:
    level:
        ROOT: WARN
        com.kairos: WARN

spring:
    devtools:
        restart:
            enabled: false
    resources:
      add-mappings: false
    mvc:
      throw-exception-if-no-handler-found: true

server:
    port: 8080